
export const DYLAN_QUOTES: string[] = [
  "You don't need a weatherman to know which way the wind blows.",
  "A man is a success if he gets up in the morning and gets to bed at night, and in between he does what he wants to do.",
  "All I can do is be me, whoever that is.",
  "Behind every beautiful thing, there's some kind of pain.",
  "I was born a long way from where I belong and I am on my way home.",
  "Sometimes it's not enough to know what things mean, sometimes you have to know what things don't mean.",
  "To live outside the law, you must be honest.",
  "I define nothing. Not beauty, not patriotism. I take each thing as it is, without prior rules about what it should be.",
  "People seldom do what they believe in. They do what is convenient, then repent.",
  "Yesterday's just a memory, tomorrow is never what it's supposed to be.",
  "May your heart always be joyful, may your song always be sung.",
  "He not busy being born is busy dying.",
  "The answer, my friend, is blowin' in the wind.",
  "I'll let you be in my dreams if I can be in yours.",
  "Take me on a trip upon your magic swirlin' ship.",
  "Money doesn't talk, it swears.",
  "All the truth in the world adds up to one big lie.",
  "I was so much older then, I'm younger than that now.",
  "Chaos is a friend of mine.",
  "I accept chaos, I'm not sure whether it accepts me.",
  "A song is anything that can walk by itself.",
  "I consider myself a poet first and a musician second.",
  "You can't be wise and in love at the same time.",
  "Inspiration is hard to come by. You have to take it where you find it.",
  "I think a hero is any person really intent on making this a better place for all people.",
  "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
  "All this talk about equality. The only thing people really have in common is that they are all going to die.",
  "I say there're no depressed words just depressed minds."
];
