
export const INITIAL_RAW_PHRASES: string[] = [
  "Absolute chaos", "Velvet rain", "Dusty road", "Midnight train", "Golden tear",
  "Autumn wind", "Bitter truth", "Canyon echo", "Desert bloom", "Endless road",
  "Fading light", "Frozen tear", "Gentle hum", "Ghostly sigh", "Haunted mile",
  "Hollow sound", "Iron will", "Jagged edge", "Lost cause", "Lucid dream",
  "Magic hour", "Neon glow", "Noble heart", "Open sky", "Quiet night",
  "Raging fire", "Sacred ground", "Shattered glass", "Silent scream", "Silver moon",
  "Steel resolve", "Stolen kiss", "Sudden chill", "Sweet despair", "Tender touch",
  "Twilight zone", "Twisted vine", "Velvet fog", "Violent storm", "Wandering soul",
  "Whispered word", "Wild desire", "Worn-out shoes", "Amber glow", "Ashen sky",
  "Barren field", "Borrowed time", "Broken vow", "Burning bridge", "Changing tide",
  "Crooked smile", "Crystal stream", "Dancing flame", "Distant shore", "Empty room",
  "Fallen star", "Fatal flaw", "Final bow", "Forgotten song", "Frozen heart",
  "Guiding light", "Hidden scar", "Humble prayer", "Inner voice", "Last goodbye",
  "Lonely hour", "Misty dawn", "Narrow path", "New beginning", "Old guitar",
  "Pale moonlight", "Perfect crime", "Phantom limb", "Quiet town", "Rebel yell",
  "Restless heart", "Rising sun", "Rocky ground", "Sacred oath", "Sad cafe",
  "Secret wish", "Shadow play", "Shining armor", "Silver lining", "Simple truth",
  "Sleeping giant", "Slow burn", "Smoking gun", "Sole survivor", "Somber mood",
  "Southern drawl", "Steel guitar", "Stone cold", "Stormy weather", "Strange brew",
  "Streetlight halo", "Sudden fear", "Summer rain", "Sweet surrender", "Tangled web",
  "Tattered flag", "Temple bell", "Thin disguise", "Thousand lies", "Thunder road",
  "Timeless tale", "Troubled mind", "True north", "Twilight years", "Twisted fate",
  "Unbroken chain", "Uncommon man", "Unknown soldier", "Unseen hand", "Untold story",
  "Velvet glove", "Victory lap", "Vintage wine", "Wasted youth", "Weathered face",
  "Whiskey neat", "White knuckle", "Wild frontier", "Winter chill", "Wooden spoon",
  "Wounded knee", "Yellow moon", "Yesterday's news", "Young blood", "Zero hour",
  "Zigzag Trail", "Zillion Stars"
];
